### ISSUE TITLE
Local install issue

### ISSUE THREAD

**Issue by davoMM** [18F/dolores-landingham-slack-bot#248]
Hi,

I'm experimenting with this app and having trouble connecting this app to Slack with a local install. I have got to the point where I am able to add an employee but when I queue up a message, it won't send. The test message won't work either. I've added my Slack API token to the .env file. Am I missing something obvious?

If you need any more info regarding my setup please let me know. I really appreciate your help on this!

**Comment by jessieay** [comment]
Hi! 
Message send through delayed job so my guess would be that you aren't working off the delayed jobs. Are you running the worker process? The easiest way to do that locally is to run the app with foreman rather than rails server. See https://github.com/18F/dolores-landingham-slack-bot/blob/develop/CONTRIBUTING.md#app-setup for setup steps if you haven't seen that already.

Congrats on getting this far! I know the app setup is not that easy, so I appreciate you putting in the effort. Any suggestions or Pull requests with improved setup or setup instructions would be much appreciated! 🌈

**Comment by davoMM** [comment]
Thanks for the quick response! Setup was a bit tricky but I was able to get up and running (just not w/ Slack yet...).

I'm currently running foreman at the default port specified in the .foreman file (5000). It is hosting the app and I see that once a minute it is running `onboarding_message.send` but nothing is going out.

**Comment by jessieay** [comment]
Hm ok, I bet we can figure this out. Can you join this public Slack channel so we can discuss in real time: https://gsa-tts.slack.com/messages/opensource-public/

**Comment by davoMM** [comment]
I can! Where can I send my email for invite?

**Comment by jessieay** [comment]
Oh sorry, I thought you could just join , didn't realize the process had changed.

Looks like now the process is to fill this out: https://chat.18f.gov/

In the meantime, I've been debugging locally and am seeing the same thing as you. If you remove the `.delay` in Line 17 of `app/controllers/test_messages_controller.rb` that enables messages to send as a short term solution.

**Comment by davoMM** [comment]
Removing `.delay` did the trick! I'm able to rule out that the Slack API Token wasn't configured correctly. I've also filled out the form for the open source channel. Thanks so much!
